/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'resolved' : boolean,
  'alertType' : string,
  'studentId' : Principal,
  'createdAt' : Time,
  'classId' : bigint,
  'percentage' : bigint,
}
export interface AttendanceRecord {
  'id' : bigint,
  'status' : string,
  'studentId' : Principal,
  'classId' : bigint,
  'markedAt' : Time,
  'sessionId' : bigint,
}
export interface AttendanceSession {
  'id' : bigint,
  'status' : string,
  'facultyId' : Principal,
  'date' : Time,
  'classId' : bigint,
}
export interface AttendanceStats {
  'attended' : bigint,
  'totalSessions' : bigint,
  'percentage' : bigint,
}
export interface BulkAttendanceEntry {
  'status' : string,
  'studentId' : Principal,
}
export interface Class {
  'id' : bigint,
  'facultyId' : Principal,
  'subject' : string,
  'name' : string,
  'createdAt' : Time,
  'section' : string,
  'studentIds' : Array<Principal>,
  'schedule' : string,
}
export type Time = bigint;
export interface User {
  'id' : Principal,
  'facultyId' : [] | [string],
  'studentId' : [] | [string],
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
  'department' : [] | [string],
}
export interface UserProfile {
  'facultyId' : [] | [string],
  'studentId' : [] | [string],
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'department' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'faculty' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bulkMarkAttendance' : ActorMethod<
    [bigint, Array<BulkAttendanceEntry>],
    Array<bigint>
  >,
  'closeAttendanceSession' : ActorMethod<[bigint], undefined>,
  'createAttendanceSession' : ActorMethod<[bigint, Time], bigint>,
  'createClass' : ActorMethod<
    [string, string, string, Array<Principal>, string],
    bigint
  >,
  'createUser' : ActorMethod<
    [
      Principal,
      string,
      string,
      UserRole,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'deleteClass' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllClassesWithStats' : ActorMethod<[], Array<[Class, AttendanceStats]>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAttendanceSessionDetails' : ActorMethod<
    [bigint],
    { 'records' : Array<AttendanceRecord>, 'session' : AttendanceSession }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClassAttendanceStats' : ActorMethod<
    [bigint],
    Array<
      {
        'studentId' : Principal,
        'attended' : bigint,
        'totalSessions' : bigint,
        'percentage' : bigint,
      }
    >
  >,
  'getEnrolledClasses' : ActorMethod<[], Array<Class>>,
  'getFacultyClasses' : ActorMethod<[], Array<Class>>,
  'getStudentAlerts' : ActorMethod<[], Array<Alert>>,
  'getStudentAttendanceByClass' : ActorMethod<[bigint], AttendanceStats>,
  'getStudentAttendanceHistory' : ActorMethod<
    [[] | [bigint], [] | [Time], [] | [Time]],
    Array<AttendanceRecord>
  >,
  'getSystemAnalytics' : ActorMethod<
    [],
    {
      'lowAttendanceCount' : bigint,
      'totalClasses' : bigint,
      'avgAttendance' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersByRole' : ActorMethod<[UserRole], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[bigint, Principal, string], bigint>,
  'reopenAttendanceSession' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAttendance' : ActorMethod<[bigint, string], undefined>,
  'updateClass' : ActorMethod<
    [bigint, string, string, string, Array<Principal>, string],
    undefined
  >,
  'updateUser' : ActorMethod<
    [
      Principal,
      string,
      string,
      UserRole,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];