/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkAttendanceEntry = IDL.Record({
  'status' : IDL.Text,
  'studentId' : IDL.Principal,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'faculty' : IDL.Null,
  'student' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'alertType' : IDL.Text,
  'studentId' : IDL.Principal,
  'createdAt' : Time,
  'classId' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const Class = IDL.Record({
  'id' : IDL.Nat,
  'facultyId' : IDL.Principal,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'section' : IDL.Text,
  'studentIds' : IDL.Vec(IDL.Principal),
  'schedule' : IDL.Text,
});
export const AttendanceStats = IDL.Record({
  'attended' : IDL.Nat,
  'totalSessions' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'facultyId' : IDL.Opt(IDL.Text),
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'department' : IDL.Opt(IDL.Text),
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'studentId' : IDL.Principal,
  'classId' : IDL.Nat,
  'markedAt' : Time,
  'sessionId' : IDL.Nat,
});
export const AttendanceSession = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'facultyId' : IDL.Principal,
  'date' : Time,
  'classId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'facultyId' : IDL.Opt(IDL.Text),
  'studentId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'department' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bulkMarkAttendance' : IDL.Func(
      [IDL.Nat, IDL.Vec(BulkAttendanceEntry)],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'closeAttendanceSession' : IDL.Func([IDL.Nat], [], []),
  'createAttendanceSession' : IDL.Func([IDL.Nat, Time], [IDL.Nat], []),
  'createClass' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Principal), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteClass' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllClassesWithStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Class, AttendanceStats))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAttendanceSessionDetails' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'records' : IDL.Vec(AttendanceRecord),
          'session' : AttendanceSession,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClassAttendanceStats' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'studentId' : IDL.Principal,
            'attended' : IDL.Nat,
            'totalSessions' : IDL.Nat,
            'percentage' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getEnrolledClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getFacultyClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getStudentAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getStudentAttendanceByClass' : IDL.Func(
      [IDL.Nat],
      [AttendanceStats],
      ['query'],
    ),
  'getStudentAttendanceHistory' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getSystemAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'lowAttendanceCount' : IDL.Nat,
          'totalClasses' : IDL.Nat,
          'avgAttendance' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'reopenAttendanceSession' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAttendance' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateClass' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Principal), IDL.Text],
      [],
      [],
    ),
  'updateUser' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkAttendanceEntry = IDL.Record({
    'status' : IDL.Text,
    'studentId' : IDL.Principal,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'faculty' : IDL.Null,
    'student' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'alertType' : IDL.Text,
    'studentId' : IDL.Principal,
    'createdAt' : Time,
    'classId' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const Class = IDL.Record({
    'id' : IDL.Nat,
    'facultyId' : IDL.Principal,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'section' : IDL.Text,
    'studentIds' : IDL.Vec(IDL.Principal),
    'schedule' : IDL.Text,
  });
  const AttendanceStats = IDL.Record({
    'attended' : IDL.Nat,
    'totalSessions' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'facultyId' : IDL.Opt(IDL.Text),
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'department' : IDL.Opt(IDL.Text),
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'studentId' : IDL.Principal,
    'classId' : IDL.Nat,
    'markedAt' : Time,
    'sessionId' : IDL.Nat,
  });
  const AttendanceSession = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'facultyId' : IDL.Principal,
    'date' : Time,
    'classId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'facultyId' : IDL.Opt(IDL.Text),
    'studentId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'department' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bulkMarkAttendance' : IDL.Func(
        [IDL.Nat, IDL.Vec(BulkAttendanceEntry)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'closeAttendanceSession' : IDL.Func([IDL.Nat], [], []),
    'createAttendanceSession' : IDL.Func([IDL.Nat, Time], [IDL.Nat], []),
    'createClass' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Principal), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteClass' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllClassesWithStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Class, AttendanceStats))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAttendanceSessionDetails' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'records' : IDL.Vec(AttendanceRecord),
            'session' : AttendanceSession,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClassAttendanceStats' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'studentId' : IDL.Principal,
              'attended' : IDL.Nat,
              'totalSessions' : IDL.Nat,
              'percentage' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getEnrolledClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getFacultyClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getStudentAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getStudentAttendanceByClass' : IDL.Func(
        [IDL.Nat],
        [AttendanceStats],
        ['query'],
      ),
    'getStudentAttendanceHistory' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(Time), IDL.Opt(Time)],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getSystemAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'lowAttendanceCount' : IDL.Nat,
            'totalClasses' : IDL.Nat,
            'avgAttendance' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'reopenAttendanceSession' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAttendance' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateClass' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Principal),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateUser' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };